services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment: 
      - PUID=1000
      - PGID=1000
      - TZ = America/Los_Angeles
    volumes:
      - /srv/jellyfin:/config
      - /home/carl/data/media:/data/media
    ports:
      - 8096:8096
    restart: unless-stopped
