services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ = America/Los_Angeles
    volumes:
      - /srv/prowlarr:/config
    ports:
      - 9696:9696

