services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ = America/Los_Angeles
    volumes:
      - /srv/radarr:/config
      - /home/carl/data:/data
    ports:
      - 7878:7878

